# Generated by Django 4.1.4 on 2022-12-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationregistry', '0006_alter_stations_site_profile_image_gen_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('attrib1', models.CharField(db_index=True, max_length=100)),
                ('attrib2', models.CharField(db_index=True, max_length=100)),
                ('attrib3', models.CharField(db_index=True, max_length=100)),
                ('attrib4', models.CharField(db_index=True, max_length=100)),
                ('attrib5', models.CharField(db_index=True, max_length=100)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricTypes',
            fields=[
                ('metric_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_dt', models.DateField(db_index=True)),
                ('data_val', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regstats.metrics')),
                ('station_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stationstatus')),
            ],
        ),
        migrations.AddField(
            model_name='metrics',
            name='metric_type',
            field=models.ForeignKey(help_text='Metric Type', on_delete=django.db.models.deletion.DO_NOTHING, to='regstats.metrictypes'),
        ),
        migrations.CreateModel(
            name='MetricMappings',
            fields=[
                ('metric_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_val', models.CharField(db_index=True, help_text='Station Entry Source Value', max_length=200)),
                ('target_val', models.CharField(help_text='Target Metric Name', max_length=200)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(help_text='Assigned Metric', on_delete=django.db.models.deletion.DO_NOTHING, to='regstats.metrics')),
                ('metric_type', models.ForeignKey(help_text='Metric Type', on_delete=django.db.models.deletion.DO_NOTHING, to='regstats.metrictypes')),
            ],
        ),
    ]
