# Generated by Django 4.1.4 on 2022-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='attrib1',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='attrib2',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='attrib3',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='attrib4',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='attrib5',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
