# Generated by Django 4.1.4 on 2022-12-19 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0002_alter_metrics_attrib1_alter_metrics_attrib2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='lst_updt_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
