# Generated by Django 4.1.4 on 2022-12-19 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0003_alter_metrics_lst_updt_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricmappings',
            name='lst_updt_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
