# Generated by Django 4.1.4 on 2022-12-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0006_alter_stations_site_profile_image_gen_dt'),
        ('regstats', '0004_alter_metricmappings_lst_updt_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, default=None, max_length=3)),
                ('province', models.CharField(db_index=True, default='unknown', max_length=100, null=True)),
                ('city', models.CharField(db_index=True, default='unknown', max_length=100, null=True)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metricmappings',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GeoStats',
            fields=[
                ('geo_stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_val', models.IntegerField(default=0)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regstats.geography')),
                ('station_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stationstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyMappings',
            fields=[
                ('geo_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_country_code', models.CharField(db_index=True, max_length=3)),
                ('source_provincee', models.CharField(db_index=True, max_length=100)),
                ('source_city', models.CharField(db_index=True, max_length=100)),
                ('target_country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('target_province', models.CharField(blank=True, max_length=100, null=True)),
                ('target_city', models.CharField(blank=True, max_length=100, null=True)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regstats.geography')),
            ],
        ),
    ]
