# Generated by Django 4.1.4 on 2022-12-19 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0005_geography_alter_metricmappings_lst_updt_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostats',
            name='report_dt',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
