# Generated by Django 4.1.4 on 2022-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0006_geostats_report_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographymappings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, help_text='latitude value provided by the weather station client', max_digits=10),
        ),
        migrations.AddField(
            model_name='geographymappings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=11),
        ),
    ]
