# Generated by Django 4.1.4 on 2022-12-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0008_alter_geography_lst_updt_ts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geographymappings',
            old_name='source_provincee',
            new_name='source_province',
        ),
    ]
