# Generated by Django 4.1.4 on 2022-12-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0009_rename_source_provincee_geographymappings_source_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default=None, max_length=50)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('country_code2', models.CharField(max_length=3)),
                ('iso_3166_code', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=20, null=True)),
                ('sub_region', models.CharField(max_length=50, null=True)),
                ('region_code', models.IntegerField(null=True)),
                ('sub_region_code', models.IntegerField(null=True)),
                ('intermediate_region_code', models.IntegerField(null=True)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='geography',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='geographymappings',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metricmappings',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metrictypes',
            name='lst_updt_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
