# Generated by Django 4.1.4 on 2022-12-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0010_countries_alter_geography_lst_updt_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='countries',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='sub_region',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
