# Generated by Django 4.1.4 on 2022-12-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regstats', '0011_alter_countries_name_alter_countries_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='intermediate_region',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
