# Generated by Django 4.1.3 on 2022-12-12 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLBlackList',
            fields=[
                ('url_blacklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.URLField(db_index=True, help_text='Domain/base URL that we are going to blacklist', max_length=50, unique=True)),
                ('url_reason', models.CharField(max_length=100)),
                ('lst_updt_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_url', models.URLField(db_index=True, help_text='url provided by the weather station client upon registration', max_length=250, unique=True)),
                ('valid_url_yn', models.BooleanField(default=False, help_text='Flag that indicates the URL provided is active (returns 200 response)')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='latitude value provided by the weather station client', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='longitude value provided by the weather station client', max_digits=11)),
                ('location_city', models.CharField(default=None, max_length=100, null=True)),
                ('location_province', models.CharField(default=None, max_length=100, null=True)),
                ('location_country_code', models.CharField(default=None, max_length=3, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('station_type', models.CharField(max_length=100)),
                ('station_model', models.CharField(max_length=150)),
                ('weewx_info', models.CharField(max_length=64)),
                ('python_info', models.CharField(max_length=64)),
                ('platform_info', models.CharField(max_length=150)),
                ('last_ip_address', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('register_dt', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the station registry record was first created.')),
                ('last_entry_dt', models.DateTimeField(help_text='Last entry datetime stamp.')),
                ('last_url_check_dt', models.DateTimeField(help_text='Last time the URL was checked to see if it was still active.', null=True)),
                ('site_profile_image_gen_dt', models.DateTimeField(help_text='Last timestamp of when the stations profile image was created.', null=True)),
                ('station_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stationstatus')),
            ],
        ),
        migrations.CreateModel(
            name='StationExtensions',
            fields=[
                ('station_extension_id', models.AutoField(primary_key=True, serialize=False)),
                ('extension_name', models.CharField(max_length=150)),
                ('extension_version', models.CharField(max_length=20)),
                ('extension_description', models.CharField(max_length=255)),
                ('entry_dt', models.DateTimeField(auto_now_add=True)),
                ('stations', models.ForeignKey(help_text='Station ID from the Stations Table.', on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stations')),
            ],
        ),
        migrations.CreateModel(
            name='StationEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_dt', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('station_url', models.URLField(db_index=True, help_text='url provided by the weather station client upon registration', max_length=250)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='latitude value provided by the weather station client', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('description', models.CharField(max_length=255, null=True)),
                ('station_type', models.CharField(max_length=100)),
                ('station_model', models.CharField(max_length=150)),
                ('weewx_info', models.CharField(max_length=64)),
                ('python_info', models.CharField(max_length=64)),
                ('platform_info', models.CharField(max_length=150)),
                ('last_ip_address', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('stations', models.ForeignKey(help_text='Station ID from the Stations Table.', on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stations')),
            ],
        ),
    ]
