# Generated by Django 4.1.3 on 2022-12-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stationstatus'),
        ),
    ]
