# Generated by Django 4.1.3 on 2022-12-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0002_alter_stations_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stationregistry.stationstatus'),
        ),
    ]
