# Generated by Django 4.1.3 on 2022-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0003_alter_stations_station_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='station_status',
        ),
        migrations.AddField(
            model_name='stations',
            name='station_status_d',
            field=models.IntegerField(default=1),
        ),
    ]
