# Generated by Django 4.1.3 on 2022-12-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0004_remove_stations_station_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='station_status_d',
            new_name='station_status_id',
        ),
    ]
