# Generated by Django 4.1.4 on 2022-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0005_rename_station_status_d_stations_station_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='site_profile_image_gen_dt',
            field=models.DateTimeField(default=None, help_text='Last timestamp of when the stations profile image was created.', null=True),
        ),
    ]
