# Generated by Django 4.1.4 on 2022-12-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0006_alter_stations_site_profile_image_gen_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='station_site_image',
            field=models.CharField(default=None, help_text='Thumbnail of the Weather Stations home page.', max_length=100, null=True),
        ),
    ]
