# Generated by Django 4.1.4 on 2022-12-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0007_stations_station_site_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationentry',
            old_name='stations',
            new_name='station_id',
        ),
    ]
