# Generated by Django 4.1.4 on 2022-12-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0008_rename_stations_stationentry_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationentry',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='stationextensions',
            old_name='stations',
            new_name='station',
        ),
    ]
