# Generated by Django 4.1.4 on 2023-01-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationregistry', '0009_rename_station_id_stationentry_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationentry',
            name='config_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stationentry',
            name='entry_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='config_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='entry_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='StationExtensions',
        ),
    ]
